# Basic Site Settings
locale                   : "en-US"
site_theme               : "contrast"

title                    : "Yunseong Jeon"
name                     : "Yunseong Jeon"
description              : "System-level optimization of AI inference"

url                      : https://ys0333.github.io
baseurl                  : ""
repository               : "ys0333/ys0333.github.io"

# Author
author:
  avatar           : "profile.png"
  name             : "Yunseong Jeon"
  bio              : "M.S. student focusing on system-level optimization of VLM and VLA inference, with an emphasis on latency reduction and efficient execution."
  location         : "Seoul, South Korea"
  employer         : "Kookmin University"
  email            : "kb0316@kookmin.ac.kr"

  # Academic
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"

  # GitHub
  github           : "ys0333"
